#!/usr/bin/env python

from mpd import MPDClient
import os
import subprocess as proc

button_cmd = { '1': 'toggle', '4': 'prev', '5': 'next' }

if __name__ == '__main__':
    client = MPDClient()
    client.timeout = 10
    client.idletimeout = None
    client.connect('localhost', 6600)

    song = client.currentsong()
    if song:
        artist = song['artist']
        title = song['title']
        status = client.status()
        state = status['state']
        if 'time' in status:
            time = list(map(int, status['time'].split(':')))
        else:
            time = None
        icon = '\uf001'

        if state == 'play':
            icon = '\uf04b'
        elif state == 'pause':
            icon = '\uf04c'
        elif state == 'stop':
            icon = '\uf04d'
        text = '{} {} - {}'.format(icon, artist, title)
        if time:
            text += ' ({0}:{2:02}/{1}:{3:02})'.format(
                    time[0] // 60, time[1] // 60, time[0] % 60, time[1] % 60)
    else:
        text = ''
    print(text)

    button = os.environ.get('BLOCK_BUTTON')
    cmd = button_cmd.get(button)
    if cmd:
        proc.Popen(['mpc', cmd], stdin=proc.DEVNULL, stdout=proc.DEVNULL)
