#!/usr/bin/env python
import sys
import os
import subprocess
import html
sys.path.append(os.path.expanduser('~/.config/i3'))
from winicon import icon_for_window

fmt_str = '{}<b>{}</b>'

if __name__ == '__main__':
    id = subprocess.run(['xdotool', 'getactivewindow'],
            stdout=subprocess.PIPE).stdout
    name = subprocess.run(['xdotool', 'getwindowname', id],
            stdout=subprocess.PIPE).stdout if id else b''
    id = int(id.decode()) if id else None
    name = name.decode().strip()
    if name.startswith('ranger:'):
        sname = 'ranger'
    else:
        _, _, sname = name.rpartition(' - ')
    icon = ' {} '.format(icon_for_window(id)) if id else ''
    title = '{} '.format(html.escape(name)) if name else ''
    abbr = '{} '.format(html.escape(sname)) if sname else ''
    full_text = fmt_str.format(icon, title) if title else ''
    short_text = fmt_str.format(icon, abbr) if abbr else ''
    print(full_text)
    print(short_text)
    print('#ffffff')
