#!/usr/bin/env python

import i3ipc
import subprocess
import signal
import sys

i3 = i3ipc.Connection()

# exit gracefully when ctrl+c is pressed
def signal_handler(signal, frame):
    i3.main_quit()
    sys.exit(0)
signal.signal(signal.SIGINT, signal_handler)
signal.signal(signal.SIGTERM, signal_handler)

def on_change(i3, e):
    if e.change in ['focus', 'close', 'move', 'title']:
        subprocess.run(['pkill', '-RTMIN+11', 'i3blocks'])
i3.on('workspace', on_change)
i3.on('window', on_change)
i3.main()
